"""add santa tables

Revision ID: 84abfe2ccee0
Revises: 30ebf99ca8b5
Create Date: 2023-11-19 00:14:00.604161

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '84abfe2ccee0'
down_revision: Union[str, None] = '30ebf99ca8b5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('santa_participant',
    sa.Column('santa_id', sa.Integer(), nullable=False),
    sa.Column('recipient_id', sa.Integer(), nullable=False),
    sa.Column('has_shipped', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('santa_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('santa_participant')
    # ### end Alembic commands ###
