"""add has_failed column to image delete table

Revision ID: 5a838b753ec1
Revises: d02095aef70e
Create Date: 2023-10-23 06:01:59.111572

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5a838b753ec1'
down_revision: Union[str, None] = 'd02095aef70e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('image_message_to_delete', sa.Column('has_failed', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('image_message_to_delete', 'has_failed')
    # ### end Alembic commands ###
