"""add user channel settings

Revision ID: 928ee4a72f48
Revises: 84abfe2ccee0
Create Date: 2023-12-14 12:24:45.595580

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '928ee4a72f48'
down_revision: Union[str, None] = 'b1deb87ac586'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_channel_settings',
    sa.Column('guild_id', sa.Integer(), nullable=False),
    sa.Column('channel_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('delete_after', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('guild_id', 'channel_id', 'user_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_channel_settings')
    # ### end Alembic commands ###
