"""Add baby month milestone channel

Revision ID: d94c1b403928
Revises: 8a96c485c490
Create Date: 2024-02-05 14:21:08.331697

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd94c1b403928'
down_revision: Union[str, None] = '8a96c485c490'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('guild_config', sa.Column('baby_month_milestone_channel_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('guild_config', 'baby_month_milestone_channel_id')
    # ### end Alembic commands ###
