"""added poll models

Revision ID: c7a45ca9ec78
Revises: 09591365eb72
Create Date: 2024-03-19 21:29:07.135384

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c7a45ca9ec78'
down_revision: Union[str, None] = '09591365eb72'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('poll_question',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('message_id', sa.Integer(), nullable=True),
    sa.Column('guild_id', sa.Integer(), nullable=False),
    sa.Column('channel_id', sa.Integer(), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.Column('text', sa.String(), nullable=False),
    sa.Column('is_anonymous', sa.Boolean(), nullable=False),
    sa.Column('is_multi_choice', sa.Boolean(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('is_open', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_poll_question_author_id'), 'poll_question', ['author_id'], unique=False)
    op.create_index(op.f('ix_poll_question_channel_id'), 'poll_question', ['channel_id'], unique=False)
    op.create_index(op.f('ix_poll_question_guild_id'), 'poll_question', ['guild_id'], unique=False)
    op.create_index(op.f('ix_poll_question_message_id'), 'poll_question', ['message_id'], unique=False)
    op.create_table('poll_choice',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('text', sa.String(), nullable=False),
    sa.Column('ordinal', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['poll_question.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('poll_response',
    sa.Column('choice_id', sa.Integer(), nullable=False),
    sa.Column('respondent_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['choice_id'], ['poll_choice.id'], ),
    sa.PrimaryKeyConstraint('choice_id', 'respondent_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('poll_response')
    op.drop_table('poll_choice')
    op.drop_index(op.f('ix_poll_question_message_id'), table_name='poll_question')
    op.drop_index(op.f('ix_poll_question_guild_id'), table_name='poll_question')
    op.drop_index(op.f('ix_poll_question_channel_id'), table_name='poll_question')
    op.drop_index(op.f('ix_poll_question_author_id'), table_name='poll_question')
    op.drop_table('poll_question')
    # ### end Alembic commands ###
