"""added error log channel setting

Revision ID: bfabbcd595c6
Revises: 8a96c485c490
Create Date: 2024-02-08 11:23:37.156362

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bfabbcd595c6'
down_revision: Union[str, None] = '8a96c485c490'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('guild_config', sa.Column('error_logging_channel_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('guild_config', 'error_logging_channel_id')
    # ### end Alembic commands ###
