"""added activity_role table

Revision ID: 1a3cc964095c
Revises: d94c1b403928
Create Date: 2024-03-07 00:08:27.373375

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1a3cc964095c'
down_revision: Union[str, None] = 'd94c1b403928'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('activity_role',
    sa.Column('guild_id', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('role_name', sa.String(), nullable=True),
    sa.Column('min', sa.Integer(), nullable=True),
    sa.Column('max', sa.Integer(), nullable=True),
    sa.Column('should_notify', sa.Boolean(), nullable=False),
    sa.Column('rolling_month_window', sa.Integer(), nullable=False, server_default="1"),
    sa.PrimaryKeyConstraint('guild_id', 'role_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('activity_role')
    # ### end Alembic commands ###
