"""added grace period to activity_role

Revision ID: 09591365eb72
Revises: 1a3cc964095c
Create Date: 2024-03-07 11:43:44.811717

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '09591365eb72'
down_revision: Union[str, None] = '1a3cc964095c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('activity_role', sa.Column('grace_period_months', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('activity_role', 'grace_period_months')
    # ### end Alembic commands ###
